### ISSUE TITLE
CQRS / Event Sourcing

### ISSUE THREAD

**Issue by andyl** [Nebo15/sage#21]
Does Sage work with Commanded or some other CQRS / Event-Sourcing Framework?

**Comment by AndrewDryga** [comment]
@andyl Short answer - I don't know. 

We never used any CQRS frameworks in our projects, but we did use some ideas from them, eg. "event sourcing" itself. And I don't think I would use them any soon because I've stopped doing fintecth and other domains are not that sensitive to problems it solves.

Generally, if there is a place for failure handling (where you need to compensate created effects) and the framework doesn't solve it for you - there is place for Sagas. 

With some event sourcing frameworks you may get your local state covered because you can compensate event by adding a new one that reverses previous operation, which is pretty much the same as just using transactions. But if you still synchronize state with external services - I don't think there is a way for a framework to handle it for you.

**Comment by andyl** [comment]
@AndrewDryga thanks for explaining.  Sage looks great I will study it and thanks for publishing this code.

**Comment by AndrewDryga** [comment]
@andyl you are welcome. If you come up with a nice usage pattern - please ping me and we can write a blog/doc on it, I think it would be beneficial for the community.
